### ISSUE TITLE
well the shader mess up or something

### ISSUE THREAD

**Issue by RayRiver21** [Thorinair/LumaDriver-for-ChilloutVR#1]
so I installed it to my world the right way, I uploaded it my world it won't work, unless I toggle the mirror on its works and I turn it off it quit working, so I tried to debug it and still not get it to work

**Comment by Thorinair** [comment]
There is not enough info in this issue report to actually help... Make sure you haven't parented it to the mirror or something, because what you describe sounds like it might be parented to the mirror. It would be beneficial if you can provide some screenshots of the setup.

**Comment by RayRiver21** [comment]
https://user-images.githubusercontent.com/79367957/211618797-a9615ced-7391-4248-a9eb-b44d7ce491c1.mp4
![Screenshot 2023-01-10 122147](https://user-images.githubusercontent.com/79367957/211619547-e042f518-b034-442f-9a23-23ceecaf6f56.png) Mirror HQ
![Screenshot 2023-01-10 122359](https://user-images.githubusercontent.com/79367957/211620057-7f16945d-be03-4979-99ab-e7c61ab8af64.png) Mirroe LQ
![Screenshot 2023-01-10 122552](https://user-images.githubusercontent.com/79367957/211620711-815b832f-1800-4d66-a5bc-f01c4aaa90b9.png) Luma Drive
![Screenshot 2023-01-10 122640](https://user-images.githubusercontent.com/79367957/211620770-0eb23d25-c095-4f96-bfd4-8af4feda651d.png) added rt-audiolink

ill send you a video, luma and mirror screenshots

**Comment by RayRiver21** [comment]
update sorry

https://user-images.githubusercontent.com/79367957/211626381-aa289ac8-40bd-4c42-9e27-23b82b666287.mp4
I deleted the mirrors and still not working
![Screenshot 2023-01-10 125655](https://user-images.githubusercontent.com/79367957/211626740-f1f1bf3e-1916-45eb-9310-9d5ced7a015b.png)

**Comment by Thorinair** [comment]
It looks like you modified both the clipping planes and the location of the LumaDriver object. Please revert everything to how it was set in the prefab.

**Comment by RayRiver21** [comment]
it works I'm sorry is my ocd it say y100000 I was like why again sorry
